name: employee_management_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #core Packages
  get: ^4.7.2

  # Screen Utls for Responsive 
  flutter_screenutil: ^5.9.0

  # firebase
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
