// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHgpNukN07GvsU4s5RlmS1PMdcQIpuLKA',
    appId: '1:6384196166:web:b9f30fd899f1033baec847',
    messagingSenderId: '6384196166',
    projectId: 'ems-app-35e0c',
    authDomain: 'ems-app-35e0c.firebaseapp.com',
    storageBucket: 'ems-app-35e0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofbkedFVyoSiMZhjvcVeWQXtnO-JESVw',
    appId: '1:6384196166:android:2c2d996e42ae729faec847',
    messagingSenderId: '6384196166',
    projectId: 'ems-app-35e0c',
    storageBucket: 'ems-app-35e0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaON_x8fGETIv0gREPNKIVvGpDJASIgAI',
    appId: '1:6384196166:ios:1b0e198ce145dad5aec847',
    messagingSenderId: '6384196166',
    projectId: 'ems-app-35e0c',
    storageBucket: 'ems-app-35e0c.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaON_x8fGETIv0gREPNKIVvGpDJASIgAI',
    appId: '1:6384196166:ios:1b0e198ce145dad5aec847',
    messagingSenderId: '6384196166',
    projectId: 'ems-app-35e0c',
    storageBucket: 'ems-app-35e0c.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHgpNukN07GvsU4s5RlmS1PMdcQIpuLKA',
    appId: '1:6384196166:web:9eb173e9a22f013daec847',
    messagingSenderId: '6384196166',
    projectId: 'ems-app-35e0c',
    authDomain: 'ems-app-35e0c.firebaseapp.com',
    storageBucket: 'ems-app-35e0c.firebasestorage.app',
  );
}
